# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_four_news_portal',
            name='document_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='form_one_news_portal',
            name='document_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='form_three_news_portal',
            name='document_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='form_two_news_portal',
            name='document_name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
