# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0002_auto_20170830_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_one_news_portal',
            name='document_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
