# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0004_auto_20170830_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_four_news_portal',
            name='document_file',
        ),
        migrations.RemoveField(
            model_name='form_four_news_portal',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='form_one_news_portal',
            name='document_file',
        ),
        migrations.RemoveField(
            model_name='form_one_news_portal',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='form_three_news_portal',
            name='document_file',
        ),
        migrations.RemoveField(
            model_name='form_three_news_portal',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='form_two_news_portal',
            name='document_file',
        ),
        migrations.RemoveField(
            model_name='form_two_news_portal',
            name='document_name',
        ),
    ]
