# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0007_auto_20170830_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_rules',
            old_name='rule_eight',
            new_name='rule',
        ),
        migrations.RemoveField(
            model_name='school_rules',
            name='rule_five',
        ),
        migrations.RemoveField(
            model_name='school_rules',
            name='rule_four',
        ),
        migrations.RemoveField(
            model_name='school_rules',
            name='rule_nine',
        ),
        migrations.RemoveField(
            model_name='school_rules',
            name='rule_one',
        ),
        migrations.RemoveField(
            model_name='school_rules',
            name='rule_seven',
        ),
        migrations.RemoveField(
            model_name='school_rules',
            name='rule_six',
        ),
        migrations.RemoveField(
            model_name='school_rules',
            name='rule_ten',
        ),
        migrations.RemoveField(
            model_name='school_rules',
            name='rule_three',
        ),
        migrations.RemoveField(
            model_name='school_rules',
            name='rule_two',
        ),
    ]
