# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0008_auto_20170830_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_rules',
            old_name='rule',
            new_name='rule_title',
        ),
        migrations.AddField(
            model_name='school_rules',
            name='rule_description',
            field=models.TextField(blank=True),
        ),
    ]
