# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0009_auto_20170830_1705'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School_view',
            new_name='School_beautification',
        ),
    ]
