# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogues', '0010_auto_20170830_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcse_year', models.IntegerField(default=2007)),
                ('grades_A_plain', models.IntegerField(default=0)),
                ('grades_A_minus', models.IntegerField(default=0)),
                ('grades_B_plus', models.IntegerField(default=0)),
                ('grades_B_plain', models.IntegerField(default=0)),
                ('grades_B_minus', models.IntegerField(default=0)),
                ('grades_C_plus', models.IntegerField(default=0)),
                ('grades_C_plain', models.IntegerField(default=0)),
                ('grades_C_minus', models.IntegerField(default=0)),
                ('grades_D_plus', models.IntegerField(default=0)),
                ('grades_D_plain', models.IntegerField(default=0)),
                ('grades_D_minus', models.IntegerField(default=0)),
                ('grades_E', models.IntegerField(default=0)),
                ('grades_F', models.IntegerField(default=0)),
                ('school_mean_score', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
