# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0013_school_peace_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_general_information',
            name='mail_icon',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
