# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0015_auto_20170831_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_performance',
            name='kcse_year',
            field=models.IntegerField(default=2007),
        ),
    ]
