# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0018_remove_school_photo_gallery_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form_three_classes',
            new_name='School_form_four_classes',
        ),
        migrations.RenameModel(
            old_name='Form_two_classes',
            new_name='School_form_one_classes',
        ),
        migrations.RenameModel(
            old_name='Form_one_classes',
            new_name='School_form_three_classes',
        ),
        migrations.RenameModel(
            old_name='Form_four_classes',
            new_name='School_form_two_classes',
        ),
        migrations.AlterField(
            model_name='school_general_information',
            name='school_emailaddress',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='school_general_information',
            name='school_phone_number',
            field=models.CharField(max_length=200),
        ),
    ]
