# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0021_auto_20170906_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_general_information',
            name='school_website',
            field=models.TextField(null=True),
        ),
    ]
