# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0022_school_general_information_school_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_general_information',
            name='other_phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
