# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 13:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogues', '0024_school_core_values_core_value_ten'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_events_calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='School Events Entries', max_length=300)),
                ('jan', models.CharField(max_length=250, null=True)),
                ('feb', models.CharField(max_length=250, null=True)),
                ('mar', models.CharField(max_length=250, null=True)),
                ('apr', models.CharField(max_length=250, null=True)),
                ('may', models.CharField(max_length=250, null=True)),
                ('jun', models.CharField(max_length=250, null=True)),
                ('jul', models.CharField(max_length=250, null=True)),
                ('aug', models.CharField(max_length=250, null=True)),
                ('sep', models.CharField(max_length=250, null=True)),
                ('octo', models.CharField(max_length=250, null=True)),
                ('nov', models.CharField(max_length=250, null=True)),
                ('dec', models.CharField(max_length=250, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
