# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0028_auto_20170915_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_general_information',
            name='address_icon',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
