# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0031_auto_20170925_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_events_april',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='school_events_august',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='school_events_december',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='school_events_february',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='school_events_january',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='school_events_july',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='school_events_june',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='school_events_march',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='school_events_may',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='school_events_november',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='school_events_october',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='school_events_september',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='school_events_april',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_events_august',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_events_december',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_events_february',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_events_january',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_events_july',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_events_june',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_events_march',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_events_may',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_events_november',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_events_october',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school_events_september',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
