# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0034_auto_20171012_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_alumnae',
            name='photob',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
