# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogues', '0037_auto_20171012_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_alumnae',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='school_alumnae',
            name='name',
        ),
        migrations.RemoveField(
            model_name='school_alumnae',
            name='photob',
        ),
    ]
